ci:
  skip:
  - pylint
  - mypy
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md,markdown']
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
    exclude: tests/data/.*
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: pretty-format-json
    args:
    - --indent
    - '4'
    - --autofix
    - --no-sort-keys
  - id: check-toml
  - id: fix-encoding-pragma
    args:
    - --remove
- repo: https://github.com/psf/black
  rev: 2ddea293a88919650266472186620a98a4a8bb37  # frozen: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 4e97b170469b7c8ef29afe944ebfb057791457aa  # frozen: 5.11.4
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-no-eval
  - id: python-no-log-warn
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types: [python]
  - id: pylint
    name: pylint
    entry: pylint
    args:
    - '-s'
    - 'no'
    language: system
    types: [python]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: d0cf8a7a8e09127a5a61c0644a823544e32f492b  # frozen: 0.2.2
  hooks:
  - id: yamlfmt
    args:
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
    - --width
    - '120'
    - -e
    - -p
